### ISSUE TITLE
Missing line breaks when copying selected texts

### ISSUE THREAD

**Issue by lihenggui** [adrianjagielak/flutter_markdown_selectionarea#1]
Hi @adrianjagielak 
I used [flutter_markdown_selectionarea](https://github.com/adrianjagielak/flutter_markdown_selectionarea) plugin in my Flutter app to support Selectable texts in the app.

But I found that after clicking 'copy', all line breaks are gone. 

For example: If you copy selected content in the app:

![image](https://user-images.githubusercontent.com/5171312/233850935-e079ced9-78ef-43c8-8205-80da207d1bd4.png)

The content in the clipboard would be 
```
Heading 3This is a paragraph of text. You can make text bold or italic.You can create lists:•Item 1•Item 2•Item 3Or numbered lists:
```

I wonder if it is a bug in the library or not. The expected behavior is that the content with line breaks can be copied normally.

**Comment by adrianjagielak** [comment]
Its expected behavior, at least for now, as each paragraph is rendered into its own RichText widget and Flutter does not yet nicely handle inserting spaces/line breaks into text copied from multiple widgets.

I refer you to this: [Copy text in SelectionArea is not like copying text from HTML #104548](https://github.com/flutter/flutter/issues/104548)

There is a work in progress to add support for text separators, PR: [Add support for separators in text copied from SelectableRegion #121112](https://github.com/flutter/flutter/pull/121112)
You could probably try to copy those changes to your local Flutter installation (basic.dart, framework.dart, scrollable.dart, and selectable_region.dart)

**Comment by lihenggui** [comment]
Thank you!

**Comment by sezeryavuz** [comment]
Check here maybe you can find solution. https://github.com/flutter/flutter/issues/104548#issuecomment-2051481671
